{
 "title": "Starlink",
 "description": "Starlink dish metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "DishID",
    "label": "Dish ID",
    "query": {
     "query": "label_values(starlink_dish_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Route",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "starlink_dish_location_info{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "starlink_dish_location_info{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Obstruction Map",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_map{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Update Pending",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_install_pending{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is Heating",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_is_heating{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mast Not Near Vertical",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_mast_not_near_vertical{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Motors Stuck",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_motors_stuck{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Roaming",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_roaming{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Obstruction Map Reset",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_obstruction_map_reset{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Save Idle",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_power_save_idle{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSU Thermal Throttle",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_power_supply_thermal_throttle{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Obstructed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_currently_obstructed{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low Motor Current",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_low_motor_current{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lower Signal",
   "type": "stat",
   "description": "Lower Signal than Predicted",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_lower_signal_than_predicted{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fast Move",
   "type": "stat",
   "description": "Moving too fast for policy",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_moving_too_fast_for_policy{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Move while not Mobile",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_moving_while_not_mobile{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Eth Speeds",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_slow_eth_speeds{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unexpected Location",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_unexpected_location{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thermal Throttle",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_thermal_throttle{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thermal Shutdown",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_thermal_shutdown{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dish Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "System Clock",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "starlink_dish_gps_time_s{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPS Time (Seconds)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_gps_time_s{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power draw (Current)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_power_watt_current{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power draw (15 min Avg)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_power_watt_avg_15min{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected GPS Satellites",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 17 },
   "targets": [
    {
     "expr": "starlink_dish_gps_sats{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_uptime_seconds{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{build_id}}"
    }
   ]
  },
  {
   "title": "Device ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{device_id}}"
    }
   ]
  },
  {
   "title": "Boot Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_boot_count{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{software_version}}"
    }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{hardware_version}}"
    }
   ]
  },
  {
   "title": "Dish Mobility Class",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_mobility_class{instance=\"$DishID\"}",
     "legendFormat": "{{mobility_class}}"
    }
   ]
  },
  {
   "title": "Generation Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{generationNumber}}"
    }
   ]
  },
  {
   "title": "Software Update State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_software_update_state{instance=\"$DishID\"}",
     "legendFormat": "{{software_update_state}}"
    }
   ]
  },
  {
   "title": "Disablement Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_disablement_code{instance=\"$DishID\"}",
     "legendFormat": "{{disablement_code}}"
    }
   ]
  },
  {
   "title": "UTC Offset",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{utc_offset}}"
    }
   ]
  },
  {
   "title": "Country Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "GPS Valid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_gps_valid{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPS Sats ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_gps_sats{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "starlink_dish_location_info{instance=\"$DishID\"}",
     "legendFormat": "{{lat}}"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "starlink_dish_location_info{instance=\"$DishID\"}",
     "legendFormat": "{{alt}}"
    }
   ]
  },
  {
   "title": "Level Dish Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{level_dish_mode}}"
    }
   ]
  },
  {
   "title": "Power Save Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{power_save_mode}}"
    }
   ]
  },
  {
   "title": "Location Request",
   "type": "stat",
   "description": "LOCAL, NONE",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{location_request_mode}}"
    }
   ]
  },
  {
   "title": "Snow Melt Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{snow_melt_mode}}"
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "starlink_dish_location_info{instance=\"$DishID\"}",
     "legendFormat": "{{lon}}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "starlink_dish_location_info{instance=\"$DishID\"}",
     "legendFormat": "{{location_source}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "PoP Latency (gRPC API)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "starlink_dish_pop_ping_latency_seconds{instance=\"$DishID\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"starlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"minimum_response_ms\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"starlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dns_query\")\n  |> filter(fn: (r) => r[\"_field\"] == \"query_time_ms\" )\n  |> filter(fn: (r) => r[\"result\"] == \"success\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Phy Rx Beam SNR Avg",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "starlink_dish_phy_rx_beam_snr_avg{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "starlink_dish_uplink_throughput_bytes{instance=\"$DishID\"} / 1000000 * -1",
     "legendFormat": "__auto"
    },
    {
     "expr": "starlink_dish_downlink_throughput_bytes{instance=\"$DishID\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pop Ping Drop Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "starlink_dish_pop_ping_drop_ratio{instance=\"$DishID\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "starlink_dish_power_watt_current{instance=\"$DishID\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dish Temperate Center",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "starlink_dish_tCenter{instance=\"$DishID\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initialization Duration Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }
  },
  {
   "title": "Attitude Initialization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{attitudeInitialization}}"
    }
   ]
  },
  {
   "title": "Burst Detected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{burstDetected}}"
    }
   ]
  },
  {
   "title": "ekf Converged",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{ekfConverged}}"
    }
   ]
  },
  {
   "title": "first Cplane",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{firstCplane}}"
    }
   ]
  },
  {
   "title": "first PopPing",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{firstPopPing}}"
    }
   ]
  },
  {
   "title": "gpsValid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{gpsValid}}"
    }
   ]
  },
  {
   "title": "initial Network Entry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{initialNetworkEntry}}"
    }
   ]
  },
  {
   "title": "Network Schedule",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{networkSchedule}}"
    }
   ]
  },
  {
   "title": "rfReady",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{rfReady}}"
    }
   ]
  },
  {
   "title": "stable Connection",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_initialization_duration_seconds{instance=\"$DishID\"}",
     "legendFormat": "{{stableConnection}}"
    }
   ]
  },
  {
   "title": "Max Theta Deg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_map{instance=\"$DishID\"}",
     "legendFormat": "{{max_theta_deg}}"
    }
   ]
  },
  {
   "title": "Obstructed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_currently_obstructed{instance=\"$DishID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alignment and Obstruction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Attitude Estimation State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alignment_stats{instance=\"$DishID\"}",
     "legendFormat": "{{attitudeEstimationState}}"
    }
   ]
  },
  {
   "title": "Attitude Uncertainty Deg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alignment_stats{instance=\"$DishID\"}",
     "legendFormat": "{{attitudeUncertaintyDeg}}"
    }
   ]
  },
  {
   "title": "Boresight Elevation Deg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alignment_stats{instance=\"$DishID\"}",
     "legendFormat": "{{boresightElevationDeg}}"
    }
   ]
  },
  {
   "title": "Desired Boresight Elevation Deg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alignment_stats{instance=\"$DishID\"}",
     "legendFormat": "{{desiredBoresightElevationDeg}}"
    }
   ]
  },
  {
   "title": "Boresight Azimuth Deg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alignment_stats{instance=\"$DishID\"}",
     "legendFormat": "{{boresightAzimuthDeg}}"
    }
   ]
  },
  {
   "title": "Desired Boresight Azimuth Deg",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alignment_stats{instance=\"$DishID\"}",
     "legendFormat": "{{desiredBoresightAzimuthDeg}}"
    }
   ]
  },
  {
   "title": "Reference Frame",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_map{instance=\"$DishID\"}",
     "legendFormat": "{{reference_frame}}"
    }
   ]
  }
 ]
}