// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spacex/api/device/dish.proto

package device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DishState int32

const (
	DishState_UNKNOWN   DishState = 0
	DishState_CONNECTED DishState = 1
	DishState_SEARCHING DishState = 2
	DishState_BOOTING   DishState = 3
)

var DishState_name = map[int32]string{
	0: "UNKNOWN",
	1: "CONNECTED",
	2: "SEARCHING",
	3: "BOOTING",
}

var DishState_value = map[string]int32{
	"UNKNOWN":   0,
	"CONNECTED": 1,
	"SEARCHING": 2,
	"BOOTING":   3,
}

func (x DishState) String() string {
	return proto.EnumName(DishState_name, int32(x))
}

func (DishState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{0}
}

type DishOutage_Cause int32

const (
	DishOutage_UNKNOWN          DishOutage_Cause = 0
	DishOutage_BOOTING          DishOutage_Cause = 1
	DishOutage_STOWED           DishOutage_Cause = 2
	DishOutage_THERMAL_SHUTDOWN DishOutage_Cause = 3
	DishOutage_NO_SCHEDULE      DishOutage_Cause = 4
	DishOutage_NO_SATS          DishOutage_Cause = 5
	DishOutage_OBSTRUCTED       DishOutage_Cause = 6
	DishOutage_NO_DOWNLINK      DishOutage_Cause = 7
	DishOutage_NO_PINGS         DishOutage_Cause = 8
)

var DishOutage_Cause_name = map[int32]string{
	0: "UNKNOWN",
	1: "BOOTING",
	2: "STOWED",
	3: "THERMAL_SHUTDOWN",
	4: "NO_SCHEDULE",
	5: "NO_SATS",
	6: "OBSTRUCTED",
	7: "NO_DOWNLINK",
	8: "NO_PINGS",
}

var DishOutage_Cause_value = map[string]int32{
	"UNKNOWN":          0,
	"BOOTING":          1,
	"STOWED":           2,
	"THERMAL_SHUTDOWN": 3,
	"NO_SCHEDULE":      4,
	"NO_SATS":          5,
	"OBSTRUCTED":       6,
	"NO_DOWNLINK":      7,
	"NO_PINGS":         8,
}

func (x DishOutage_Cause) String() string {
	return proto.EnumName(DishOutage_Cause_name, int32(x))
}

func (DishOutage_Cause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{4, 0}
}

type SetTestModeRequest_RfMode int32

const (
	SetTestModeRequest_RX     SetTestModeRequest_RfMode = 0
	SetTestModeRequest_IDLE   SetTestModeRequest_RfMode = 1
	SetTestModeRequest_TX     SetTestModeRequest_RfMode = 2
	SetTestModeRequest_CAL    SetTestModeRequest_RfMode = 3
	SetTestModeRequest_USER   SetTestModeRequest_RfMode = 4
	SetTestModeRequest_NORMAL SetTestModeRequest_RfMode = 420
)

var SetTestModeRequest_RfMode_name = map[int32]string{
	0:   "RX",
	1:   "IDLE",
	2:   "TX",
	3:   "CAL",
	4:   "USER",
	420: "NORMAL",
}

var SetTestModeRequest_RfMode_value = map[string]int32{
	"RX":     0,
	"IDLE":   1,
	"TX":     2,
	"CAL":    3,
	"USER":   4,
	"NORMAL": 420,
}

func (x SetTestModeRequest_RfMode) String() string {
	return proto.EnumName(SetTestModeRequest_RfMode_name, int32(x))
}

func (SetTestModeRequest_RfMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{17, 0}
}

type DishStowRequest struct {
	Unstow               bool     `protobuf:"varint,1,opt,name=unstow,proto3" json:"unstow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishStowRequest) Reset()         { *m = DishStowRequest{} }
func (m *DishStowRequest) String() string { return proto.CompactTextString(m) }
func (*DishStowRequest) ProtoMessage()    {}
func (*DishStowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{0}
}

func (m *DishStowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishStowRequest.Unmarshal(m, b)
}
func (m *DishStowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishStowRequest.Marshal(b, m, deterministic)
}
func (m *DishStowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishStowRequest.Merge(m, src)
}
func (m *DishStowRequest) XXX_Size() int {
	return xxx_messageInfo_DishStowRequest.Size(m)
}
func (m *DishStowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DishStowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DishStowRequest proto.InternalMessageInfo

func (m *DishStowRequest) GetUnstow() bool {
	if m != nil {
		return m.Unstow
	}
	return false
}

type DishStowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishStowResponse) Reset()         { *m = DishStowResponse{} }
func (m *DishStowResponse) String() string { return proto.CompactTextString(m) }
func (*DishStowResponse) ProtoMessage()    {}
func (*DishStowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{1}
}

func (m *DishStowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishStowResponse.Unmarshal(m, b)
}
func (m *DishStowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishStowResponse.Marshal(b, m, deterministic)
}
func (m *DishStowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishStowResponse.Merge(m, src)
}
func (m *DishStowResponse) XXX_Size() int {
	return xxx_messageInfo_DishStowResponse.Size(m)
}
func (m *DishStowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishStowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishStowResponse proto.InternalMessageInfo

type DishGetContextRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishGetContextRequest) Reset()         { *m = DishGetContextRequest{} }
func (m *DishGetContextRequest) String() string { return proto.CompactTextString(m) }
func (*DishGetContextRequest) ProtoMessage()    {}
func (*DishGetContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{2}
}

func (m *DishGetContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetContextRequest.Unmarshal(m, b)
}
func (m *DishGetContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetContextRequest.Marshal(b, m, deterministic)
}
func (m *DishGetContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetContextRequest.Merge(m, src)
}
func (m *DishGetContextRequest) XXX_Size() int {
	return xxx_messageInfo_DishGetContextRequest.Size(m)
}
func (m *DishGetContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetContextRequest proto.InternalMessageInfo

type DishGetContextResponse struct {
	DeviceInfo                 *DeviceInfo  `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	DeviceState                *DeviceState `protobuf:"bytes,7,opt,name=device_state,json=deviceState,proto3" json:"device_state,omitempty"`
	ObstructionFraction        float32      `protobuf:"fixed32,2,opt,name=obstruction_fraction,json=obstructionFraction,proto3" json:"obstruction_fraction,omitempty"`
	ObstructionValidS          float32      `protobuf:"fixed32,3,opt,name=obstruction_valid_s,json=obstructionValidS,proto3" json:"obstruction_valid_s,omitempty"`
	ObstructionCurrent         bool         `protobuf:"varint,12,opt,name=obstruction_current,json=obstructionCurrent,proto3" json:"obstruction_current,omitempty"`
	CellId                     uint32       `protobuf:"varint,4,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	PopRackId                  uint32       `protobuf:"varint,5,opt,name=pop_rack_id,json=popRackId,proto3" json:"pop_rack_id,omitempty"`
	InitialSatelliteId         uint32       `protobuf:"varint,8,opt,name=initial_satellite_id,json=initialSatelliteId,proto3" json:"initial_satellite_id,omitempty"`
	InitialGatewayId           uint32       `protobuf:"varint,9,opt,name=initial_gateway_id,json=initialGatewayId,proto3" json:"initial_gateway_id,omitempty"`
	OnBackupBeam               bool         `protobuf:"varint,10,opt,name=on_backup_beam,json=onBackupBeam,proto3" json:"on_backup_beam,omitempty"`
	SecondsToSlotEnd           float32      `protobuf:"fixed32,6,opt,name=seconds_to_slot_end,json=secondsToSlotEnd,proto3" json:"seconds_to_slot_end,omitempty"`
	DebugTelemetryEnabled      bool         `protobuf:"varint,11,opt,name=debug_telemetry_enabled,json=debugTelemetryEnabled,proto3" json:"debug_telemetry_enabled,omitempty"`
	PopPingDropRate_15SMean    float32      `protobuf:"fixed32,13,opt,name=pop_ping_drop_rate_15s_mean,json=popPingDropRate15sMean,proto3" json:"pop_ping_drop_rate_15s_mean,omitempty"`
	PopPingLatencyMs_15SMean   float32      `protobuf:"fixed32,14,opt,name=pop_ping_latency_ms_15s_mean,json=popPingLatencyMs15sMean,proto3" json:"pop_ping_latency_ms_15s_mean,omitempty"`
	SecondsSinceLast_1SOutage  float32      `protobuf:"fixed32,15,opt,name=seconds_since_last_1s_outage,json=secondsSinceLast1sOutage,proto3" json:"seconds_since_last_1s_outage,omitempty"`
	SecondsSinceLast_2SOutage  float32      `protobuf:"fixed32,16,opt,name=seconds_since_last_2s_outage,json=secondsSinceLast2sOutage,proto3" json:"seconds_since_last_2s_outage,omitempty"`
	SecondsSinceLast_5SOutage  float32      `protobuf:"fixed32,17,opt,name=seconds_since_last_5s_outage,json=secondsSinceLast5sOutage,proto3" json:"seconds_since_last_5s_outage,omitempty"`
	SecondsSinceLast_15SOutage float32      `protobuf:"fixed32,18,opt,name=seconds_since_last_15s_outage,json=secondsSinceLast15sOutage,proto3" json:"seconds_since_last_15s_outage,omitempty"`
	SecondsSinceLast_60SOutage float32      `protobuf:"fixed32,19,opt,name=seconds_since_last_60s_outage,json=secondsSinceLast60sOutage,proto3" json:"seconds_since_last_60s_outage,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}     `json:"-"`
	XXX_unrecognized           []byte       `json:"-"`
	XXX_sizecache              int32        `json:"-"`
}

func (m *DishGetContextResponse) Reset()         { *m = DishGetContextResponse{} }
func (m *DishGetContextResponse) String() string { return proto.CompactTextString(m) }
func (*DishGetContextResponse) ProtoMessage()    {}
func (*DishGetContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{3}
}

func (m *DishGetContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetContextResponse.Unmarshal(m, b)
}
func (m *DishGetContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetContextResponse.Marshal(b, m, deterministic)
}
func (m *DishGetContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetContextResponse.Merge(m, src)
}
func (m *DishGetContextResponse) XXX_Size() int {
	return xxx_messageInfo_DishGetContextResponse.Size(m)
}
func (m *DishGetContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetContextResponse proto.InternalMessageInfo

func (m *DishGetContextResponse) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *DishGetContextResponse) GetDeviceState() *DeviceState {
	if m != nil {
		return m.DeviceState
	}
	return nil
}

func (m *DishGetContextResponse) GetObstructionFraction() float32 {
	if m != nil {
		return m.ObstructionFraction
	}
	return 0
}

func (m *DishGetContextResponse) GetObstructionValidS() float32 {
	if m != nil {
		return m.ObstructionValidS
	}
	return 0
}

func (m *DishGetContextResponse) GetObstructionCurrent() bool {
	if m != nil {
		return m.ObstructionCurrent
	}
	return false
}

func (m *DishGetContextResponse) GetCellId() uint32 {
	if m != nil {
		return m.CellId
	}
	return 0
}

func (m *DishGetContextResponse) GetPopRackId() uint32 {
	if m != nil {
		return m.PopRackId
	}
	return 0
}

func (m *DishGetContextResponse) GetInitialSatelliteId() uint32 {
	if m != nil {
		return m.InitialSatelliteId
	}
	return 0
}

func (m *DishGetContextResponse) GetInitialGatewayId() uint32 {
	if m != nil {
		return m.InitialGatewayId
	}
	return 0
}

func (m *DishGetContextResponse) GetOnBackupBeam() bool {
	if m != nil {
		return m.OnBackupBeam
	}
	return false
}

func (m *DishGetContextResponse) GetSecondsToSlotEnd() float32 {
	if m != nil {
		return m.SecondsToSlotEnd
	}
	return 0
}

func (m *DishGetContextResponse) GetDebugTelemetryEnabled() bool {
	if m != nil {
		return m.DebugTelemetryEnabled
	}
	return false
}

func (m *DishGetContextResponse) GetPopPingDropRate_15SMean() float32 {
	if m != nil {
		return m.PopPingDropRate_15SMean
	}
	return 0
}

func (m *DishGetContextResponse) GetPopPingLatencyMs_15SMean() float32 {
	if m != nil {
		return m.PopPingLatencyMs_15SMean
	}
	return 0
}

func (m *DishGetContextResponse) GetSecondsSinceLast_1SOutage() float32 {
	if m != nil {
		return m.SecondsSinceLast_1SOutage
	}
	return 0
}

func (m *DishGetContextResponse) GetSecondsSinceLast_2SOutage() float32 {
	if m != nil {
		return m.SecondsSinceLast_2SOutage
	}
	return 0
}

func (m *DishGetContextResponse) GetSecondsSinceLast_5SOutage() float32 {
	if m != nil {
		return m.SecondsSinceLast_5SOutage
	}
	return 0
}

func (m *DishGetContextResponse) GetSecondsSinceLast_15SOutage() float32 {
	if m != nil {
		return m.SecondsSinceLast_15SOutage
	}
	return 0
}

func (m *DishGetContextResponse) GetSecondsSinceLast_60SOutage() float32 {
	if m != nil {
		return m.SecondsSinceLast_60SOutage
	}
	return 0
}

type DishOutage struct {
	Cause                DishOutage_Cause `protobuf:"varint,1,opt,name=cause,proto3,enum=SpaceX.API.Device.DishOutage_Cause" json:"cause,omitempty"`
	StartTimestampNs     int64            `protobuf:"varint,2,opt,name=start_timestamp_ns,json=startTimestampNs,proto3" json:"start_timestamp_ns,omitempty"`
	DurationNs           uint64           `protobuf:"varint,3,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	DidSwitch            bool             `protobuf:"varint,4,opt,name=did_switch,json=didSwitch,proto3" json:"did_switch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DishOutage) Reset()         { *m = DishOutage{} }
func (m *DishOutage) String() string { return proto.CompactTextString(m) }
func (*DishOutage) ProtoMessage()    {}
func (*DishOutage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{4}
}

func (m *DishOutage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishOutage.Unmarshal(m, b)
}
func (m *DishOutage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishOutage.Marshal(b, m, deterministic)
}
func (m *DishOutage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishOutage.Merge(m, src)
}
func (m *DishOutage) XXX_Size() int {
	return xxx_messageInfo_DishOutage.Size(m)
}
func (m *DishOutage) XXX_DiscardUnknown() {
	xxx_messageInfo_DishOutage.DiscardUnknown(m)
}

var xxx_messageInfo_DishOutage proto.InternalMessageInfo

func (m *DishOutage) GetCause() DishOutage_Cause {
	if m != nil {
		return m.Cause
	}
	return DishOutage_UNKNOWN
}

func (m *DishOutage) GetStartTimestampNs() int64 {
	if m != nil {
		return m.StartTimestampNs
	}
	return 0
}

func (m *DishOutage) GetDurationNs() uint64 {
	if m != nil {
		return m.DurationNs
	}
	return 0
}

func (m *DishOutage) GetDidSwitch() bool {
	if m != nil {
		return m.DidSwitch
	}
	return false
}

type DishGetHistoryResponse struct {
	Current               uint64        `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PopPingDropRate       []float32     `protobuf:"fixed32,1001,rep,packed,name=pop_ping_drop_rate,json=popPingDropRate,proto3" json:"pop_ping_drop_rate,omitempty"`
	PopPingLatencyMs      []float32     `protobuf:"fixed32,1002,rep,packed,name=pop_ping_latency_ms,json=popPingLatencyMs,proto3" json:"pop_ping_latency_ms,omitempty"`
	DownlinkThroughputBps []float32     `protobuf:"fixed32,1003,rep,packed,name=downlink_throughput_bps,json=downlinkThroughputBps,proto3" json:"downlink_throughput_bps,omitempty"`
	UplinkThroughputBps   []float32     `protobuf:"fixed32,1004,rep,packed,name=uplink_throughput_bps,json=uplinkThroughputBps,proto3" json:"uplink_throughput_bps,omitempty"`
	Outages               []*DishOutage `protobuf:"bytes,1009,rep,name=outages,proto3" json:"outages,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *DishGetHistoryResponse) Reset()         { *m = DishGetHistoryResponse{} }
func (m *DishGetHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*DishGetHistoryResponse) ProtoMessage()    {}
func (*DishGetHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{5}
}

func (m *DishGetHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetHistoryResponse.Unmarshal(m, b)
}
func (m *DishGetHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetHistoryResponse.Marshal(b, m, deterministic)
}
func (m *DishGetHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetHistoryResponse.Merge(m, src)
}
func (m *DishGetHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_DishGetHistoryResponse.Size(m)
}
func (m *DishGetHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetHistoryResponse proto.InternalMessageInfo

func (m *DishGetHistoryResponse) GetCurrent() uint64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *DishGetHistoryResponse) GetPopPingDropRate() []float32 {
	if m != nil {
		return m.PopPingDropRate
	}
	return nil
}

func (m *DishGetHistoryResponse) GetPopPingLatencyMs() []float32 {
	if m != nil {
		return m.PopPingLatencyMs
	}
	return nil
}

func (m *DishGetHistoryResponse) GetDownlinkThroughputBps() []float32 {
	if m != nil {
		return m.DownlinkThroughputBps
	}
	return nil
}

func (m *DishGetHistoryResponse) GetUplinkThroughputBps() []float32 {
	if m != nil {
		return m.UplinkThroughputBps
	}
	return nil
}

func (m *DishGetHistoryResponse) GetOutages() []*DishOutage {
	if m != nil {
		return m.Outages
	}
	return nil
}

type DishGetStatusResponse struct {
	DeviceInfo                 *DeviceInfo           `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	DeviceState                *DeviceState          `protobuf:"bytes,2,opt,name=device_state,json=deviceState,proto3" json:"device_state,omitempty"`
	Alerts                     *DishAlerts           `protobuf:"bytes,1005,opt,name=alerts,proto3" json:"alerts,omitempty"`
	Outage                     *DishOutage           `protobuf:"bytes,1014,opt,name=outage,proto3" json:"outage,omitempty"`
	GpsStats                   *DishGpsStats         `protobuf:"bytes,1015,opt,name=gps_stats,json=gpsStats,proto3" json:"gps_stats,omitempty"`
	SecondsToFirstNonemptySlot float32               `protobuf:"fixed32,1002,opt,name=seconds_to_first_nonempty_slot,json=secondsToFirstNonemptySlot,proto3" json:"seconds_to_first_nonempty_slot,omitempty"`
	PopPingDropRate            float32               `protobuf:"fixed32,1003,opt,name=pop_ping_drop_rate,json=popPingDropRate,proto3" json:"pop_ping_drop_rate,omitempty"`
	DownlinkThroughputBps      float32               `protobuf:"fixed32,1007,opt,name=downlink_throughput_bps,json=downlinkThroughputBps,proto3" json:"downlink_throughput_bps,omitempty"`
	UplinkThroughputBps        float32               `protobuf:"fixed32,1008,opt,name=uplink_throughput_bps,json=uplinkThroughputBps,proto3" json:"uplink_throughput_bps,omitempty"`
	PopPingLatencyMs           float32               `protobuf:"fixed32,1009,opt,name=pop_ping_latency_ms,json=popPingLatencyMs,proto3" json:"pop_ping_latency_ms,omitempty"`
	ObstructionStats           *DishObstructionStats `protobuf:"bytes,1004,opt,name=obstruction_stats,json=obstructionStats,proto3" json:"obstruction_stats,omitempty"`
	StowRequested              bool                  `protobuf:"varint,1010,opt,name=stow_requested,json=stowRequested,proto3" json:"stow_requested,omitempty"`
	BoresightAzimuthDeg        float32               `protobuf:"fixed32,1011,opt,name=boresight_azimuth_deg,json=boresightAzimuthDeg,proto3" json:"boresight_azimuth_deg,omitempty"`
	BoresightElevationDeg      float32               `protobuf:"fixed32,1012,opt,name=boresight_elevation_deg,json=boresightElevationDeg,proto3" json:"boresight_elevation_deg,omitempty"`
	EthSpeedMbps               int32                 `protobuf:"varint,1016,opt,name=eth_speed_mbps,json=ethSpeedMbps,proto3" json:"eth_speed_mbps,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}              `json:"-"`
	XXX_unrecognized           []byte                `json:"-"`
	XXX_sizecache              int32                 `json:"-"`
}

func (m *DishGetStatusResponse) Reset()         { *m = DishGetStatusResponse{} }
func (m *DishGetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*DishGetStatusResponse) ProtoMessage()    {}
func (*DishGetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{6}
}

func (m *DishGetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetStatusResponse.Unmarshal(m, b)
}
func (m *DishGetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetStatusResponse.Marshal(b, m, deterministic)
}
func (m *DishGetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetStatusResponse.Merge(m, src)
}
func (m *DishGetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_DishGetStatusResponse.Size(m)
}
func (m *DishGetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetStatusResponse proto.InternalMessageInfo

func (m *DishGetStatusResponse) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *DishGetStatusResponse) GetDeviceState() *DeviceState {
	if m != nil {
		return m.DeviceState
	}
	return nil
}

func (m *DishGetStatusResponse) GetAlerts() *DishAlerts {
	if m != nil {
		return m.Alerts
	}
	return nil
}

func (m *DishGetStatusResponse) GetOutage() *DishOutage {
	if m != nil {
		return m.Outage
	}
	return nil
}

func (m *DishGetStatusResponse) GetGpsStats() *DishGpsStats {
	if m != nil {
		return m.GpsStats
	}
	return nil
}

func (m *DishGetStatusResponse) GetSecondsToFirstNonemptySlot() float32 {
	if m != nil {
		return m.SecondsToFirstNonemptySlot
	}
	return 0
}

func (m *DishGetStatusResponse) GetPopPingDropRate() float32 {
	if m != nil {
		return m.PopPingDropRate
	}
	return 0
}

func (m *DishGetStatusResponse) GetDownlinkThroughputBps() float32 {
	if m != nil {
		return m.DownlinkThroughputBps
	}
	return 0
}

func (m *DishGetStatusResponse) GetUplinkThroughputBps() float32 {
	if m != nil {
		return m.UplinkThroughputBps
	}
	return 0
}

func (m *DishGetStatusResponse) GetPopPingLatencyMs() float32 {
	if m != nil {
		return m.PopPingLatencyMs
	}
	return 0
}

func (m *DishGetStatusResponse) GetObstructionStats() *DishObstructionStats {
	if m != nil {
		return m.ObstructionStats
	}
	return nil
}

func (m *DishGetStatusResponse) GetStowRequested() bool {
	if m != nil {
		return m.StowRequested
	}
	return false
}

func (m *DishGetStatusResponse) GetBoresightAzimuthDeg() float32 {
	if m != nil {
		return m.BoresightAzimuthDeg
	}
	return 0
}

func (m *DishGetStatusResponse) GetBoresightElevationDeg() float32 {
	if m != nil {
		return m.BoresightElevationDeg
	}
	return 0
}

func (m *DishGetStatusResponse) GetEthSpeedMbps() int32 {
	if m != nil {
		return m.EthSpeedMbps
	}
	return 0
}

type DishGetObstructionMapRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishGetObstructionMapRequest) Reset()         { *m = DishGetObstructionMapRequest{} }
func (m *DishGetObstructionMapRequest) String() string { return proto.CompactTextString(m) }
func (*DishGetObstructionMapRequest) ProtoMessage()    {}
func (*DishGetObstructionMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{7}
}

func (m *DishGetObstructionMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetObstructionMapRequest.Unmarshal(m, b)
}
func (m *DishGetObstructionMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetObstructionMapRequest.Marshal(b, m, deterministic)
}
func (m *DishGetObstructionMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetObstructionMapRequest.Merge(m, src)
}
func (m *DishGetObstructionMapRequest) XXX_Size() int {
	return xxx_messageInfo_DishGetObstructionMapRequest.Size(m)
}
func (m *DishGetObstructionMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetObstructionMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetObstructionMapRequest proto.InternalMessageInfo

type DishGetObstructionMapResponse struct {
	NumRows              uint32    `protobuf:"varint,1,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	NumCols              uint32    `protobuf:"varint,2,opt,name=num_cols,json=numCols,proto3" json:"num_cols,omitempty"`
	Snr                  []float32 `protobuf:"fixed32,3,rep,packed,name=snr,proto3" json:"snr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DishGetObstructionMapResponse) Reset()         { *m = DishGetObstructionMapResponse{} }
func (m *DishGetObstructionMapResponse) String() string { return proto.CompactTextString(m) }
func (*DishGetObstructionMapResponse) ProtoMessage()    {}
func (*DishGetObstructionMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{8}
}

func (m *DishGetObstructionMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetObstructionMapResponse.Unmarshal(m, b)
}
func (m *DishGetObstructionMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetObstructionMapResponse.Marshal(b, m, deterministic)
}
func (m *DishGetObstructionMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetObstructionMapResponse.Merge(m, src)
}
func (m *DishGetObstructionMapResponse) XXX_Size() int {
	return xxx_messageInfo_DishGetObstructionMapResponse.Size(m)
}
func (m *DishGetObstructionMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetObstructionMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetObstructionMapResponse proto.InternalMessageInfo

func (m *DishGetObstructionMapResponse) GetNumRows() uint32 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *DishGetObstructionMapResponse) GetNumCols() uint32 {
	if m != nil {
		return m.NumCols
	}
	return 0
}

func (m *DishGetObstructionMapResponse) GetSnr() []float32 {
	if m != nil {
		return m.Snr
	}
	return nil
}

type DishAlerts struct {
	MotorsStuck          bool     `protobuf:"varint,1,opt,name=motors_stuck,json=motorsStuck,proto3" json:"motors_stuck,omitempty"`
	ThermalThrottle      bool     `protobuf:"varint,3,opt,name=thermal_throttle,json=thermalThrottle,proto3" json:"thermal_throttle,omitempty"`
	ThermalShutdown      bool     `protobuf:"varint,2,opt,name=thermal_shutdown,json=thermalShutdown,proto3" json:"thermal_shutdown,omitempty"`
	MastNotNearVertical  bool     `protobuf:"varint,5,opt,name=mast_not_near_vertical,json=mastNotNearVertical,proto3" json:"mast_not_near_vertical,omitempty"`
	UnexpectedLocation   bool     `protobuf:"varint,4,opt,name=unexpected_location,json=unexpectedLocation,proto3" json:"unexpected_location,omitempty"`
	SlowEthernetSpeeds   bool     `protobuf:"varint,6,opt,name=slow_ethernet_speeds,json=slowEthernetSpeeds,proto3" json:"slow_ethernet_speeds,omitempty"`
	Roaming              bool     `protobuf:"varint,7,opt,name=roaming,proto3" json:"roaming,omitempty"`
	InstallPending       bool     `protobuf:"varint,8,opt,name=install_pending,json=installPending,proto3" json:"install_pending,omitempty"`
	IsHeating            bool     `protobuf:"varint,9,opt,name=is_heating,json=isHeating,proto3" json:"is_heating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishAlerts) Reset()         { *m = DishAlerts{} }
func (m *DishAlerts) String() string { return proto.CompactTextString(m) }
func (*DishAlerts) ProtoMessage()    {}
func (*DishAlerts) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{9}
}

func (m *DishAlerts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishAlerts.Unmarshal(m, b)
}
func (m *DishAlerts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishAlerts.Marshal(b, m, deterministic)
}
func (m *DishAlerts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishAlerts.Merge(m, src)
}
func (m *DishAlerts) XXX_Size() int {
	return xxx_messageInfo_DishAlerts.Size(m)
}
func (m *DishAlerts) XXX_DiscardUnknown() {
	xxx_messageInfo_DishAlerts.DiscardUnknown(m)
}

var xxx_messageInfo_DishAlerts proto.InternalMessageInfo

func (m *DishAlerts) GetMotorsStuck() bool {
	if m != nil {
		return m.MotorsStuck
	}
	return false
}

func (m *DishAlerts) GetThermalThrottle() bool {
	if m != nil {
		return m.ThermalThrottle
	}
	return false
}

func (m *DishAlerts) GetThermalShutdown() bool {
	if m != nil {
		return m.ThermalShutdown
	}
	return false
}

func (m *DishAlerts) GetMastNotNearVertical() bool {
	if m != nil {
		return m.MastNotNearVertical
	}
	return false
}

func (m *DishAlerts) GetUnexpectedLocation() bool {
	if m != nil {
		return m.UnexpectedLocation
	}
	return false
}

func (m *DishAlerts) GetSlowEthernetSpeeds() bool {
	if m != nil {
		return m.SlowEthernetSpeeds
	}
	return false
}

func (m *DishAlerts) GetRoaming() bool {
	if m != nil {
		return m.Roaming
	}
	return false
}

func (m *DishAlerts) GetInstallPending() bool {
	if m != nil {
		return m.InstallPending
	}
	return false
}

func (m *DishAlerts) GetIsHeating() bool {
	if m != nil {
		return m.IsHeating
	}
	return false
}

type DishGpsStats struct {
	GpsValid             bool     `protobuf:"varint,1,opt,name=gps_valid,json=gpsValid,proto3" json:"gps_valid,omitempty"`
	GpsSats              uint32   `protobuf:"varint,2,opt,name=gps_sats,json=gpsSats,proto3" json:"gps_sats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishGpsStats) Reset()         { *m = DishGpsStats{} }
func (m *DishGpsStats) String() string { return proto.CompactTextString(m) }
func (*DishGpsStats) ProtoMessage()    {}
func (*DishGpsStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{10}
}

func (m *DishGpsStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGpsStats.Unmarshal(m, b)
}
func (m *DishGpsStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGpsStats.Marshal(b, m, deterministic)
}
func (m *DishGpsStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGpsStats.Merge(m, src)
}
func (m *DishGpsStats) XXX_Size() int {
	return xxx_messageInfo_DishGpsStats.Size(m)
}
func (m *DishGpsStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGpsStats.DiscardUnknown(m)
}

var xxx_messageInfo_DishGpsStats proto.InternalMessageInfo

func (m *DishGpsStats) GetGpsValid() bool {
	if m != nil {
		return m.GpsValid
	}
	return false
}

func (m *DishGpsStats) GetGpsSats() uint32 {
	if m != nil {
		return m.GpsSats
	}
	return 0
}

type DishObstructionStats struct {
	CurrentlyObstructed              bool      `protobuf:"varint,5,opt,name=currently_obstructed,json=currentlyObstructed,proto3" json:"currently_obstructed,omitempty"`
	FractionObstructed               float32   `protobuf:"fixed32,1,opt,name=fraction_obstructed,json=fractionObstructed,proto3" json:"fraction_obstructed,omitempty"`
	ValidS                           float32   `protobuf:"fixed32,4,opt,name=valid_s,json=validS,proto3" json:"valid_s,omitempty"`
	WedgeFractionObstructed          []float32 `protobuf:"fixed32,2,rep,packed,name=wedge_fraction_obstructed,json=wedgeFractionObstructed,proto3" json:"wedge_fraction_obstructed,omitempty"`
	WedgeAbsFractionObstructed       []float32 `protobuf:"fixed32,3,rep,packed,name=wedge_abs_fraction_obstructed,json=wedgeAbsFractionObstructed,proto3" json:"wedge_abs_fraction_obstructed,omitempty"`
	AvgProlongedObstructionDurationS float32   `protobuf:"fixed32,6,opt,name=avg_prolonged_obstruction_duration_s,json=avgProlongedObstructionDurationS,proto3" json:"avg_prolonged_obstruction_duration_s,omitempty"`
	AvgProlongedObstructionIntervalS float32   `protobuf:"fixed32,7,opt,name=avg_prolonged_obstruction_interval_s,json=avgProlongedObstructionIntervalS,proto3" json:"avg_prolonged_obstruction_interval_s,omitempty"`
	AvgProlongedObstructionValid     bool      `protobuf:"varint,8,opt,name=avg_prolonged_obstruction_valid,json=avgProlongedObstructionValid,proto3" json:"avg_prolonged_obstruction_valid,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}  `json:"-"`
	XXX_unrecognized                 []byte    `json:"-"`
	XXX_sizecache                    int32     `json:"-"`
}

func (m *DishObstructionStats) Reset()         { *m = DishObstructionStats{} }
func (m *DishObstructionStats) String() string { return proto.CompactTextString(m) }
func (*DishObstructionStats) ProtoMessage()    {}
func (*DishObstructionStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{11}
}

func (m *DishObstructionStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishObstructionStats.Unmarshal(m, b)
}
func (m *DishObstructionStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishObstructionStats.Marshal(b, m, deterministic)
}
func (m *DishObstructionStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishObstructionStats.Merge(m, src)
}
func (m *DishObstructionStats) XXX_Size() int {
	return xxx_messageInfo_DishObstructionStats.Size(m)
}
func (m *DishObstructionStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DishObstructionStats.DiscardUnknown(m)
}

var xxx_messageInfo_DishObstructionStats proto.InternalMessageInfo

func (m *DishObstructionStats) GetCurrentlyObstructed() bool {
	if m != nil {
		return m.CurrentlyObstructed
	}
	return false
}

func (m *DishObstructionStats) GetFractionObstructed() float32 {
	if m != nil {
		return m.FractionObstructed
	}
	return 0
}

func (m *DishObstructionStats) GetValidS() float32 {
	if m != nil {
		return m.ValidS
	}
	return 0
}

func (m *DishObstructionStats) GetWedgeFractionObstructed() []float32 {
	if m != nil {
		return m.WedgeFractionObstructed
	}
	return nil
}

func (m *DishObstructionStats) GetWedgeAbsFractionObstructed() []float32 {
	if m != nil {
		return m.WedgeAbsFractionObstructed
	}
	return nil
}

func (m *DishObstructionStats) GetAvgProlongedObstructionDurationS() float32 {
	if m != nil {
		return m.AvgProlongedObstructionDurationS
	}
	return 0
}

func (m *DishObstructionStats) GetAvgProlongedObstructionIntervalS() float32 {
	if m != nil {
		return m.AvgProlongedObstructionIntervalS
	}
	return 0
}

func (m *DishObstructionStats) GetAvgProlongedObstructionValid() bool {
	if m != nil {
		return m.AvgProlongedObstructionValid
	}
	return false
}

type DishAuthenticateResponse struct {
	Dish                 *ChallengeResponse `protobuf:"bytes,2,opt,name=dish,proto3" json:"dish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DishAuthenticateResponse) Reset()         { *m = DishAuthenticateResponse{} }
func (m *DishAuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*DishAuthenticateResponse) ProtoMessage()    {}
func (*DishAuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{12}
}

func (m *DishAuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishAuthenticateResponse.Unmarshal(m, b)
}
func (m *DishAuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishAuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *DishAuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishAuthenticateResponse.Merge(m, src)
}
func (m *DishAuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_DishAuthenticateResponse.Size(m)
}
func (m *DishAuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishAuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishAuthenticateResponse proto.InternalMessageInfo

func (m *DishAuthenticateResponse) GetDish() *ChallengeResponse {
	if m != nil {
		return m.Dish
	}
	return nil
}

type SelfTestRequest struct {
	Detailed             bool     `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfTestRequest) Reset()         { *m = SelfTestRequest{} }
func (m *SelfTestRequest) String() string { return proto.CompactTextString(m) }
func (*SelfTestRequest) ProtoMessage()    {}
func (*SelfTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{13}
}

func (m *SelfTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfTestRequest.Unmarshal(m, b)
}
func (m *SelfTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfTestRequest.Marshal(b, m, deterministic)
}
func (m *SelfTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfTestRequest.Merge(m, src)
}
func (m *SelfTestRequest) XXX_Size() int {
	return xxx_messageInfo_SelfTestRequest.Size(m)
}
func (m *SelfTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelfTestRequest proto.InternalMessageInfo

func (m *SelfTestRequest) GetDetailed() bool {
	if m != nil {
		return m.Detailed
	}
	return false
}

type SelfTestResponse struct {
	Passed               bool     `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Report               string   `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfTestResponse) Reset()         { *m = SelfTestResponse{} }
func (m *SelfTestResponse) String() string { return proto.CompactTextString(m) }
func (*SelfTestResponse) ProtoMessage()    {}
func (*SelfTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{14}
}

func (m *SelfTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfTestResponse.Unmarshal(m, b)
}
func (m *SelfTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfTestResponse.Marshal(b, m, deterministic)
}
func (m *SelfTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfTestResponse.Merge(m, src)
}
func (m *SelfTestResponse) XXX_Size() int {
	return xxx_messageInfo_SelfTestResponse.Size(m)
}
func (m *SelfTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelfTestResponse proto.InternalMessageInfo

func (m *SelfTestResponse) GetPassed() bool {
	if m != nil {
		return m.Passed
	}
	return false
}

func (m *SelfTestResponse) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

type StartDishSelfTestRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartDishSelfTestRequest) Reset()         { *m = StartDishSelfTestRequest{} }
func (m *StartDishSelfTestRequest) String() string { return proto.CompactTextString(m) }
func (*StartDishSelfTestRequest) ProtoMessage()    {}
func (*StartDishSelfTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{15}
}

func (m *StartDishSelfTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartDishSelfTestRequest.Unmarshal(m, b)
}
func (m *StartDishSelfTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartDishSelfTestRequest.Marshal(b, m, deterministic)
}
func (m *StartDishSelfTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartDishSelfTestRequest.Merge(m, src)
}
func (m *StartDishSelfTestRequest) XXX_Size() int {
	return xxx_messageInfo_StartDishSelfTestRequest.Size(m)
}
func (m *StartDishSelfTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartDishSelfTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartDishSelfTestRequest proto.InternalMessageInfo

type StartDishSelfTestResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartDishSelfTestResponse) Reset()         { *m = StartDishSelfTestResponse{} }
func (m *StartDishSelfTestResponse) String() string { return proto.CompactTextString(m) }
func (*StartDishSelfTestResponse) ProtoMessage()    {}
func (*StartDishSelfTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{16}
}

func (m *StartDishSelfTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartDishSelfTestResponse.Unmarshal(m, b)
}
func (m *StartDishSelfTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartDishSelfTestResponse.Marshal(b, m, deterministic)
}
func (m *StartDishSelfTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartDishSelfTestResponse.Merge(m, src)
}
func (m *StartDishSelfTestResponse) XXX_Size() int {
	return xxx_messageInfo_StartDishSelfTestResponse.Size(m)
}
func (m *StartDishSelfTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartDishSelfTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartDishSelfTestResponse proto.InternalMessageInfo

type SetTestModeRequest struct {
	RfMode                SetTestModeRequest_RfMode `protobuf:"varint,1,opt,name=rf_mode,json=rfMode,proto3,enum=SpaceX.API.Device.SetTestModeRequest_RfMode" json:"rf_mode,omitempty"`
	DisableLossOfCommFdir bool                      `protobuf:"varint,1001,opt,name=disable_loss_of_comm_fdir,json=disableLossOfCommFdir,proto3" json:"disable_loss_of_comm_fdir,omitempty"`
	EnableRulesOverride   bool                      `protobuf:"varint,1002,opt,name=enable_rules_override,json=enableRulesOverride,proto3" json:"enable_rules_override,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *SetTestModeRequest) Reset()         { *m = SetTestModeRequest{} }
func (m *SetTestModeRequest) String() string { return proto.CompactTextString(m) }
func (*SetTestModeRequest) ProtoMessage()    {}
func (*SetTestModeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{17}
}

func (m *SetTestModeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTestModeRequest.Unmarshal(m, b)
}
func (m *SetTestModeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTestModeRequest.Marshal(b, m, deterministic)
}
func (m *SetTestModeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTestModeRequest.Merge(m, src)
}
func (m *SetTestModeRequest) XXX_Size() int {
	return xxx_messageInfo_SetTestModeRequest.Size(m)
}
func (m *SetTestModeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTestModeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTestModeRequest proto.InternalMessageInfo

func (m *SetTestModeRequest) GetRfMode() SetTestModeRequest_RfMode {
	if m != nil {
		return m.RfMode
	}
	return SetTestModeRequest_RX
}

func (m *SetTestModeRequest) GetDisableLossOfCommFdir() bool {
	if m != nil {
		return m.DisableLossOfCommFdir
	}
	return false
}

func (m *SetTestModeRequest) GetEnableRulesOverride() bool {
	if m != nil {
		return m.EnableRulesOverride
	}
	return false
}

type SetTestModeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTestModeResponse) Reset()         { *m = SetTestModeResponse{} }
func (m *SetTestModeResponse) String() string { return proto.CompactTextString(m) }
func (*SetTestModeResponse) ProtoMessage()    {}
func (*SetTestModeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{18}
}

func (m *SetTestModeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTestModeResponse.Unmarshal(m, b)
}
func (m *SetTestModeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTestModeResponse.Marshal(b, m, deterministic)
}
func (m *SetTestModeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTestModeResponse.Merge(m, src)
}
func (m *SetTestModeResponse) XXX_Size() int {
	return xxx_messageInfo_SetTestModeResponse.Size(m)
}
func (m *SetTestModeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTestModeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTestModeResponse proto.InternalMessageInfo

type DishSetConfigRequest struct {
	DishConfig           *DishConfig `protobuf:"bytes,1,opt,name=dish_config,json=dishConfig,proto3" json:"dish_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DishSetConfigRequest) Reset()         { *m = DishSetConfigRequest{} }
func (m *DishSetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*DishSetConfigRequest) ProtoMessage()    {}
func (*DishSetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{19}
}

func (m *DishSetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishSetConfigRequest.Unmarshal(m, b)
}
func (m *DishSetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishSetConfigRequest.Marshal(b, m, deterministic)
}
func (m *DishSetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishSetConfigRequest.Merge(m, src)
}
func (m *DishSetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_DishSetConfigRequest.Size(m)
}
func (m *DishSetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DishSetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DishSetConfigRequest proto.InternalMessageInfo

func (m *DishSetConfigRequest) GetDishConfig() *DishConfig {
	if m != nil {
		return m.DishConfig
	}
	return nil
}

type DishSetConfigResponse struct {
	UpdatedDishConfig    *DishConfig `protobuf:"bytes,1,opt,name=updated_dish_config,json=updatedDishConfig,proto3" json:"updated_dish_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DishSetConfigResponse) Reset()         { *m = DishSetConfigResponse{} }
func (m *DishSetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*DishSetConfigResponse) ProtoMessage()    {}
func (*DishSetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{20}
}

func (m *DishSetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishSetConfigResponse.Unmarshal(m, b)
}
func (m *DishSetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishSetConfigResponse.Marshal(b, m, deterministic)
}
func (m *DishSetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishSetConfigResponse.Merge(m, src)
}
func (m *DishSetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_DishSetConfigResponse.Size(m)
}
func (m *DishSetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishSetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishSetConfigResponse proto.InternalMessageInfo

func (m *DishSetConfigResponse) GetUpdatedDishConfig() *DishConfig {
	if m != nil {
		return m.UpdatedDishConfig
	}
	return nil
}

type DishGetConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishGetConfigRequest) Reset()         { *m = DishGetConfigRequest{} }
func (m *DishGetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*DishGetConfigRequest) ProtoMessage()    {}
func (*DishGetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{21}
}

func (m *DishGetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetConfigRequest.Unmarshal(m, b)
}
func (m *DishGetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetConfigRequest.Marshal(b, m, deterministic)
}
func (m *DishGetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetConfigRequest.Merge(m, src)
}
func (m *DishGetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_DishGetConfigRequest.Size(m)
}
func (m *DishGetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetConfigRequest proto.InternalMessageInfo

type DishGetConfigResponse struct {
	DishConfig           *DishConfig `protobuf:"bytes,1,opt,name=dish_config,json=dishConfig,proto3" json:"dish_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DishGetConfigResponse) Reset()         { *m = DishGetConfigResponse{} }
func (m *DishGetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*DishGetConfigResponse) ProtoMessage()    {}
func (*DishGetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc52f178f72f29e, []int{22}
}

func (m *DishGetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishGetConfigResponse.Unmarshal(m, b)
}
func (m *DishGetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishGetConfigResponse.Marshal(b, m, deterministic)
}
func (m *DishGetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishGetConfigResponse.Merge(m, src)
}
func (m *DishGetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_DishGetConfigResponse.Size(m)
}
func (m *DishGetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishGetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishGetConfigResponse proto.InternalMessageInfo

func (m *DishGetConfigResponse) GetDishConfig() *DishConfig {
	if m != nil {
		return m.DishConfig
	}
	return nil
}

func init() {
	proto.RegisterEnum("SpaceX.API.Device.DishState", DishState_name, DishState_value)
	proto.RegisterEnum("SpaceX.API.Device.DishOutage_Cause", DishOutage_Cause_name, DishOutage_Cause_value)
	proto.RegisterEnum("SpaceX.API.Device.SetTestModeRequest_RfMode", SetTestModeRequest_RfMode_name, SetTestModeRequest_RfMode_value)
	proto.RegisterType((*DishStowRequest)(nil), "SpaceX.API.Device.DishStowRequest")
	proto.RegisterType((*DishStowResponse)(nil), "SpaceX.API.Device.DishStowResponse")
	proto.RegisterType((*DishGetContextRequest)(nil), "SpaceX.API.Device.DishGetContextRequest")
	proto.RegisterType((*DishGetContextResponse)(nil), "SpaceX.API.Device.DishGetContextResponse")
	proto.RegisterType((*DishOutage)(nil), "SpaceX.API.Device.DishOutage")
	proto.RegisterType((*DishGetHistoryResponse)(nil), "SpaceX.API.Device.DishGetHistoryResponse")
	proto.RegisterType((*DishGetStatusResponse)(nil), "SpaceX.API.Device.DishGetStatusResponse")
	proto.RegisterType((*DishGetObstructionMapRequest)(nil), "SpaceX.API.Device.DishGetObstructionMapRequest")
	proto.RegisterType((*DishGetObstructionMapResponse)(nil), "SpaceX.API.Device.DishGetObstructionMapResponse")
	proto.RegisterType((*DishAlerts)(nil), "SpaceX.API.Device.DishAlerts")
	proto.RegisterType((*DishGpsStats)(nil), "SpaceX.API.Device.DishGpsStats")
	proto.RegisterType((*DishObstructionStats)(nil), "SpaceX.API.Device.DishObstructionStats")
	proto.RegisterType((*DishAuthenticateResponse)(nil), "SpaceX.API.Device.DishAuthenticateResponse")
	proto.RegisterType((*SelfTestRequest)(nil), "SpaceX.API.Device.SelfTestRequest")
	proto.RegisterType((*SelfTestResponse)(nil), "SpaceX.API.Device.SelfTestResponse")
	proto.RegisterType((*StartDishSelfTestRequest)(nil), "SpaceX.API.Device.StartDishSelfTestRequest")
	proto.RegisterType((*StartDishSelfTestResponse)(nil), "SpaceX.API.Device.StartDishSelfTestResponse")
	proto.RegisterType((*SetTestModeRequest)(nil), "SpaceX.API.Device.SetTestModeRequest")
	proto.RegisterType((*SetTestModeResponse)(nil), "SpaceX.API.Device.SetTestModeResponse")
	proto.RegisterType((*DishSetConfigRequest)(nil), "SpaceX.API.Device.DishSetConfigRequest")
	proto.RegisterType((*DishSetConfigResponse)(nil), "SpaceX.API.Device.DishSetConfigResponse")
	proto.RegisterType((*DishGetConfigRequest)(nil), "SpaceX.API.Device.DishGetConfigRequest")
	proto.RegisterType((*DishGetConfigResponse)(nil), "SpaceX.API.Device.DishGetConfigResponse")
}

func init() { proto.RegisterFile("spacex/api/device/dish.proto", fileDescriptor_fcc52f178f72f29e) }

var fileDescriptor_fcc52f178f72f29e = []byte{
	// 2077 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x5b, 0x73, 0xdb, 0xc6,
	0x15, 0x8e, 0x28, 0x99, 0xa0, 0x8e, 0x64, 0x09, 0x5e, 0x59, 0x12, 0x2c, 0x5f, 0x8b, 0xb8, 0x8d,
	0xd3, 0x49, 0xe4, 0xdb, 0xd8, 0x4d, 0xda, 0x49, 0xa6, 0x12, 0x45, 0x4b, 0x4a, 0x24, 0xd2, 0x03,
	0x50, 0xb6, 0xa7, 0x2f, 0x3b, 0x2b, 0x60, 0x49, 0x62, 0x0c, 0x60, 0x51, 0xec, 0x42, 0xb2, 0xfa,
	0xd6, 0x97, 0xbe, 0xb6, 0x2f, 0xfd, 0x07, 0xfd, 0x31, 0xfd, 0x09, 0xfd, 0x0b, 0xb9, 0xda, 0xee,
	0x25, 0xed, 0x5b, 0x3b, 0x7b, 0x01, 0x48, 0x5b, 0xa4, 0x3a, 0x9e, 0x4e, 0x9f, 0xc8, 0x3d, 0xdf,
	0xf9, 0x0e, 0x76, 0x0f, 0xce, 0x6d, 0x01, 0x57, 0x78, 0x46, 0x02, 0xfa, 0xe2, 0x36, 0xc9, 0xa2,
	0xdb, 0x21, 0x3d, 0x8a, 0x02, 0x7a, 0x3b, 0x8c, 0xf8, 0x60, 0x3d, 0xcb, 0x99, 0x60, 0xe8, 0x82,
	0x2f, 0xd1, 0x67, 0xeb, 0x1b, 0x8f, 0x77, 0xd7, 0xb7, 0x14, 0xba, 0x76, 0xed, 0x34, 0x21, 0x60,
	0x49, 0xc2, 0x52, 0x4d, 0x59, 0x7b, 0x7f, 0xbc, 0x41, 0x1c, 0xb0, 0xb4, 0x17, 0xf5, 0xb5, 0x92,
	0xfb, 0x21, 0x2c, 0x6e, 0x45, 0x7c, 0xe0, 0x0b, 0x76, 0xec, 0xd1, 0x5f, 0x17, 0x94, 0x0b, 0xb4,
	0x02, 0xf5, 0x22, 0xe5, 0x82, 0x1d, 0x3b, 0x53, 0x37, 0xa6, 0x6e, 0x35, 0x3c, 0xb3, 0x72, 0x11,
	0xd8, 0x43, 0x55, 0x9e, 0xb1, 0x94, 0x53, 0x77, 0x15, 0x96, 0xa5, 0x6c, 0x9b, 0x8a, 0x26, 0x4b,
	0x05, 0x7d, 0x21, 0x8c, 0x11, 0xf7, 0x8f, 0x0d, 0x58, 0x79, 0x1b, 0xd1, 0x1c, 0xf4, 0x39, 0xcc,
	0xe9, 0xed, 0xe0, 0x28, 0xed, 0x31, 0xf5, 0x90, 0xb9, 0x7b, 0x57, 0xd7, 0x4f, 0x1d, 0xd0, 0xfc,
	0xec, 0xa6, 0x3d, 0xe6, 0x41, 0x58, 0xfd, 0x47, 0x1b, 0x30, 0x6f, 0xf8, 0x5c, 0x10, 0x41, 0x1d,
	0x4b, 0x19, 0xb8, 0x36, 0xd1, 0x80, 0x2f, 0xb5, 0x3c, 0xf3, 0x4c, 0xb5, 0x40, 0x77, 0xe1, 0x22,
	0x3b, 0xe4, 0x22, 0x2f, 0x02, 0x11, 0xb1, 0x14, 0xf7, 0x72, 0xa2, 0xfe, 0x38, 0xb5, 0x1b, 0x53,
	0xb7, 0x6a, 0xde, 0xd2, 0x08, 0xf6, 0xc8, 0x40, 0x68, 0x1d, 0x46, 0xc5, 0xf8, 0x88, 0xc4, 0x51,
	0x88, 0xb9, 0x33, 0xad, 0x18, 0x17, 0x46, 0xa0, 0x27, 0x12, 0xf1, 0xd1, 0xed, 0x37, 0xf5, 0x83,
	0x22, 0xcf, 0x69, 0x2a, 0x9c, 0x79, 0xe5, 0x52, 0x34, 0x02, 0x35, 0x35, 0x82, 0x56, 0xc1, 0x0a,
	0x68, 0x1c, 0xe3, 0x28, 0x74, 0x66, 0x6e, 0x4c, 0xdd, 0x3a, 0xef, 0xd5, 0xe5, 0x72, 0x37, 0x44,
	0xd7, 0x60, 0x2e, 0x63, 0x19, 0xce, 0x49, 0xf0, 0x5c, 0x82, 0xe7, 0x14, 0x38, 0x9b, 0xb1, 0xcc,
	0x23, 0xc1, 0xf3, 0xdd, 0x10, 0xdd, 0x81, 0x8b, 0x51, 0x1a, 0x89, 0x88, 0xc4, 0x98, 0x13, 0x41,
	0xe3, 0x38, 0x12, 0x54, 0x2a, 0x36, 0x94, 0x22, 0x32, 0x98, 0x5f, 0x42, 0xbb, 0x21, 0xfa, 0x08,
	0x4a, 0x29, 0xee, 0x13, 0x41, 0x8f, 0xc9, 0x89, 0xd4, 0x9f, 0x55, 0xfa, 0xb6, 0x41, 0xb6, 0x35,
	0xb0, 0x1b, 0xa2, 0x9b, 0xb0, 0xc0, 0x52, 0x7c, 0x48, 0x82, 0xe7, 0x45, 0x86, 0x0f, 0x29, 0x49,
	0x1c, 0x50, 0x87, 0x98, 0x67, 0xe9, 0xa6, 0x12, 0x6e, 0x52, 0x92, 0xa0, 0x8f, 0x61, 0x89, 0xd3,
	0x80, 0xa5, 0x21, 0xc7, 0x82, 0x61, 0x1e, 0x33, 0x81, 0x69, 0x1a, 0x3a, 0x75, 0xe5, 0x1f, 0xdb,
	0x40, 0x5d, 0xe6, 0xc7, 0x4c, 0xb4, 0xd2, 0x10, 0x3d, 0x84, 0xd5, 0x90, 0x1e, 0x16, 0x7d, 0x2c,
	0x68, 0x4c, 0x13, 0x2a, 0xf2, 0x13, 0x4c, 0x53, 0x72, 0x18, 0xd3, 0xd0, 0x99, 0x53, 0xd6, 0x97,
	0x15, 0xdc, 0x2d, 0xd1, 0x96, 0x06, 0xd1, 0x2f, 0xe0, 0xb2, 0x74, 0x46, 0x16, 0xa5, 0x7d, 0x1c,
	0xe6, 0xca, 0x2d, 0x82, 0xe2, 0xbb, 0x0f, 0x38, 0x4e, 0x28, 0x49, 0x9d, 0xf3, 0xea, 0x71, 0x2b,
	0x19, 0xcb, 0x1e, 0x47, 0x69, 0x7f, 0x2b, 0x97, 0x4e, 0x12, 0xf4, 0xee, 0x03, 0xbe, 0x4f, 0x49,
	0x8a, 0x3e, 0x83, 0x2b, 0x15, 0x39, 0x26, 0x82, 0xa6, 0xc1, 0x09, 0x4e, 0xf8, 0x90, 0xbd, 0xa0,
	0xd8, 0xab, 0x86, 0xbd, 0xa7, 0x35, 0xf6, 0x79, 0x49, 0xff, 0x1c, 0xae, 0x94, 0x47, 0xe4, 0x51,
	0x1a, 0x50, 0x1c, 0x13, 0x2e, 0xf0, 0x5d, 0x8e, 0x59, 0x21, 0x48, 0x9f, 0x3a, 0x8b, 0x8a, 0xee,
	0x18, 0x1d, 0x5f, 0xaa, 0xec, 0x11, 0x2e, 0xee, 0xf2, 0x8e, 0xc2, 0x27, 0xf0, 0xef, 0x55, 0x7c,
	0x7b, 0x3c, 0xff, 0xde, 0xd9, 0xfc, 0x07, 0x15, 0xff, 0xc2, 0x78, 0xfe, 0x83, 0x92, 0xff, 0x4b,
	0xb8, 0x3a, 0x6e, 0xff, 0x43, 0x03, 0x48, 0x19, 0xb8, 0x74, 0xea, 0x00, 0xff, 0xc5, 0xc2, 0xc3,
	0x3b, 0x95, 0x85, 0xa5, 0xf1, 0x16, 0x1e, 0xde, 0x31, 0x16, 0xdc, 0x3f, 0xd7, 0x00, 0x64, 0x5d,
	0x30, 0x06, 0x3f, 0x85, 0x73, 0x01, 0x29, 0x38, 0x55, 0x55, 0x60, 0xe1, 0xde, 0xfb, 0xe3, 0x92,
	0xb8, 0xd2, 0x5e, 0x6f, 0x4a, 0x55, 0x4f, 0x33, 0x64, 0x10, 0x73, 0x41, 0x72, 0x81, 0x45, 0x94,
	0x50, 0x2e, 0x48, 0x92, 0xe1, 0x94, 0xab, 0x0c, 0x9e, 0xf6, 0x6c, 0x85, 0x74, 0x4b, 0xa0, 0xcd,
	0xd1, 0x75, 0x98, 0x0b, 0x8b, 0x9c, 0xa8, 0x5c, 0x4c, 0x75, 0xda, 0xce, 0x78, 0x50, 0x8a, 0xda,
	0x1c, 0x5d, 0x05, 0x08, 0x65, 0x46, 0x1f, 0x47, 0x22, 0x18, 0xa8, 0x0c, 0x6c, 0x78, 0xb3, 0x61,
	0x14, 0xfa, 0x4a, 0xe0, 0xfe, 0x61, 0x0a, 0xce, 0xa9, 0xc7, 0xa3, 0x39, 0xb0, 0x0e, 0xda, 0x5f,
	0xb6, 0x3b, 0x4f, 0xdb, 0xf6, 0x7b, 0x72, 0xb1, 0xd9, 0xe9, 0x74, 0x77, 0xdb, 0xdb, 0xf6, 0x14,
	0x02, 0xa8, 0xfb, 0xdd, 0xce, 0xd3, 0xd6, 0x96, 0x5d, 0x43, 0x17, 0xc1, 0xee, 0xee, 0xb4, 0xbc,
	0xfd, 0x8d, 0x3d, 0xec, 0xef, 0x1c, 0x74, 0xb7, 0xa4, 0xfa, 0x34, 0x5a, 0x84, 0xb9, 0x76, 0x07,
	0xfb, 0xcd, 0x9d, 0xd6, 0xd6, 0xc1, 0x5e, 0xcb, 0x9e, 0x91, 0x7c, 0x29, 0xd8, 0xe8, 0xfa, 0xf6,
	0x39, 0xb4, 0x00, 0xd0, 0xd9, 0xf4, 0xbb, 0xde, 0x41, 0xb3, 0xdb, 0xda, 0xb2, 0xeb, 0x46, 0x5b,
	0x52, 0xf7, 0x76, 0xdb, 0x5f, 0xda, 0x16, 0x9a, 0x87, 0x46, 0xbb, 0x83, 0x1f, 0xef, 0xb6, 0xb7,
	0x7d, 0xbb, 0xe1, 0xfe, 0xa5, 0x56, 0x95, 0xd8, 0x9d, 0x88, 0x0b, 0x96, 0x9f, 0x54, 0x25, 0xd6,
	0x01, 0xab, 0x2c, 0x38, 0x53, 0xea, 0xa4, 0xe5, 0x52, 0x7a, 0xed, 0x74, 0xfe, 0x38, 0x5f, 0x59,
	0x37, 0xa6, 0x6f, 0xd5, 0xbc, 0xc5, 0xb7, 0xf2, 0x46, 0x16, 0xbd, 0x31, 0x09, 0xe3, 0x7c, 0xad,
	0xd5, 0xed, 0xb7, 0x13, 0x05, 0xfd, 0x0c, 0x56, 0x43, 0x76, 0x9c, 0xc6, 0x51, 0xfa, 0x1c, 0x8b,
	0x41, 0xce, 0x8a, 0xfe, 0x20, 0x2b, 0x04, 0x3e, 0xcc, 0xb8, 0xf3, 0x8d, 0xe6, 0x2c, 0x97, 0x78,
	0xb7, 0x82, 0x37, 0x33, 0x8e, 0xee, 0xc3, 0x72, 0x91, 0x8d, 0xa3, 0x7d, 0xab, 0x69, 0x4b, 0x1a,
	0x7d, 0x93, 0xf4, 0x09, 0x58, 0x3a, 0xec, 0xb8, 0xf3, 0x5a, 0xaa, 0x4d, 0xe8, 0x22, 0x55, 0xfc,
	0x78, 0xa5, 0xfa, 0x17, 0xf5, 0xc6, 0x77, 0x96, 0xfd, 0xbd, 0xf5, 0x45, 0xbd, 0xf1, 0xbd, 0x65,
	0xbf, 0x94, 0xbf, 0x2f, 0x2d, 0xfb, 0x95, 0xfc, 0x7d, 0x65, 0xd9, 0xaf, 0x2d, 0xf7, 0x77, 0x56,
	0xd5, 0xd7, 0x64, 0xc3, 0x28, 0xf8, 0xff, 0xad, 0x79, 0xd5, 0xde, 0xbd, 0x79, 0x3d, 0x84, 0x3a,
	0x89, 0x69, 0x2e, 0xb8, 0xf3, 0x9d, 0x35, 0xf9, 0xf1, 0x11, 0x1f, 0x6c, 0x28, 0x2d, 0xcf, 0x68,
	0x4b, 0x9e, 0xc9, 0xd2, 0x1f, 0xce, 0xe6, 0x19, 0x6f, 0x19, 0x6d, 0xf4, 0x19, 0xcc, 0xf6, 0x33,
	0xae, 0xf6, 0xcb, 0x9d, 0x7f, 0x6a, 0xea, 0xf5, 0x09, 0xd4, 0xed, 0x8c, 0xcb, 0x4d, 0x72, 0xaf,
	0xd1, 0x37, 0xff, 0x50, 0x13, 0xae, 0x8d, 0x34, 0x86, 0x5e, 0x94, 0x73, 0x81, 0x53, 0x96, 0xd2,
	0x24, 0x13, 0x27, 0xaa, 0x4f, 0xc8, 0x70, 0x92, 0x55, 0x63, 0xad, 0x6a, 0x12, 0x8f, 0xa4, 0x52,
	0xdb, 0xe8, 0xc8, 0x8e, 0x31, 0x21, 0x6c, 0xbf, 0xd1, 0xc4, 0x53, 0x61, 0x7b, 0x46, 0x18, 0xbe,
	0xd4, 0x94, 0x77, 0x0d, 0xc3, 0x57, 0x9a, 0x36, 0x36, 0x0c, 0x27, 0x24, 0xc9, 0x6b, 0x4d, 0x39,
	0x9d, 0x24, 0x07, 0x30, 0x3a, 0x2e, 0x18, 0xbf, 0x7e, 0xab, 0xfd, 0xfa, 0xc1, 0xa4, 0x57, 0x32,
	0x24, 0x68, 0xff, 0xda, 0xec, 0x2d, 0x09, 0xfa, 0x09, 0x2c, 0xc8, 0x31, 0x0d, 0xe7, 0x7a, 0x02,
	0xa3, 0xa1, 0xf3, 0x57, 0x4b, 0x55, 0xb1, 0xf3, 0x7c, 0x38, 0xdc, 0xd1, 0x50, 0x9e, 0xf1, 0x90,
	0xe5, 0x94, 0x47, 0xfd, 0x81, 0xc0, 0xe4, 0x37, 0x51, 0x52, 0x88, 0x01, 0x0e, 0x69, 0xdf, 0xf9,
	0x9b, 0x39, 0x63, 0x85, 0x6e, 0x68, 0x70, 0x8b, 0xf6, 0xa5, 0x47, 0x87, 0x24, 0x1a, 0xd3, 0x23,
	0x5d, 0x49, 0x25, 0xed, 0xef, 0xc6, 0xa3, 0x15, 0xde, 0x2a, 0x61, 0x49, 0xfc, 0x31, 0x2c, 0x50,
	0x31, 0xc0, 0x3c, 0xa3, 0x34, 0xc4, 0x89, 0x74, 0xe5, 0xbf, 0xa4, 0xfe, 0x39, 0x6f, 0x9e, 0x8a,
	0x81, 0x2f, 0xa5, 0xfb, 0x87, 0x99, 0x4c, 0xc8, 0xaf, 0x2c, 0xfb, 0xeb, 0xd1, 0x84, 0xfc, 0x87,
	0x65, 0xff, 0x60, 0xb9, 0xd7, 0xe0, 0x8a, 0xc9, 0xc3, 0x11, 0x0f, 0xec, 0x93, 0xac, 0x1c, 0x33,
	0xfb, 0x70, 0x75, 0x02, 0x6e, 0xf2, 0xf5, 0x12, 0x34, 0xd2, 0x22, 0xc1, 0x39, 0x3b, 0xe6, 0x2a,
	0x59, 0xcf, 0x7b, 0x56, 0x5a, 0x24, 0x1e, 0x3b, 0xe6, 0x25, 0x14, 0xb0, 0x58, 0xb7, 0x0d, 0x0d,
	0x35, 0x59, 0xcc, 0x91, 0x0d, 0xd3, 0x3c, 0xcd, 0x9d, 0x69, 0x55, 0x7b, 0xe4, 0x5f, 0xf7, 0xdf,
	0xa6, 0x6f, 0xe9, 0x9c, 0x42, 0x3f, 0x82, 0xf9, 0x84, 0x09, 0x96, 0xcb, 0xb4, 0x28, 0x82, 0xe7,
	0x66, 0x52, 0x9e, 0xd3, 0x32, 0x5f, 0x8a, 0xd0, 0x87, 0x60, 0x8b, 0x01, 0xcd, 0x13, 0x12, 0xab,
	0x60, 0x12, 0x22, 0xa6, 0xaa, 0xed, 0x34, 0xbc, 0x45, 0x23, 0xef, 0x1a, 0xf1, 0xa8, 0x2a, 0x1f,
	0x14, 0x42, 0xc6, 0xa6, 0xda, 0xd1, 0x50, 0xd5, 0x37, 0x62, 0x74, 0x1f, 0x56, 0x12, 0xa2, 0x32,
	0x48, 0xe0, 0x94, 0x92, 0x1c, 0x1f, 0xd1, 0x5c, 0x44, 0x01, 0x89, 0xd5, 0x5c, 0xd8, 0xf0, 0x96,
	0x24, 0xda, 0x66, 0xa2, 0x4d, 0x49, 0xfe, 0xc4, 0x40, 0x72, 0x16, 0x2d, 0x52, 0xfa, 0x22, 0xa3,
	0x81, 0xa0, 0x21, 0x8e, 0x59, 0xa0, 0x5e, 0x8f, 0x69, 0x72, 0x68, 0x08, 0xed, 0x19, 0x44, 0x8e,
	0x94, 0x3c, 0x66, 0xc7, 0x98, 0xca, 0xc7, 0xa7, 0x54, 0xe8, 0xf7, 0xc7, 0xd5, 0x34, 0xd7, 0xf0,
	0x90, 0xc4, 0x5a, 0x06, 0x52, 0xef, 0x90, 0xcb, 0x8e, 0x93, 0x33, 0x92, 0x44, 0x69, 0xdf, 0xd1,
	0x51, 0x57, 0x2e, 0xd1, 0x07, 0xb0, 0x18, 0xa5, 0x5c, 0x90, 0x38, 0xc6, 0x19, 0x4d, 0x43, 0xa9,
	0xd1, 0x50, 0x1a, 0x0b, 0x46, 0xfc, 0x58, 0x4b, 0x65, 0x07, 0x8e, 0x38, 0x1e, 0x50, 0x22, 0xa4,
	0xce, 0xac, 0xee, 0xc0, 0x11, 0xdf, 0xd1, 0x02, 0xf7, 0x11, 0xcc, 0x8f, 0x56, 0x18, 0x74, 0x59,
	0x97, 0x25, 0x35, 0x88, 0x1b, 0xff, 0xcb, 0xa2, 0xa3, 0xc6, 0x6f, 0xf9, 0x6e, 0x55, 0xcd, 0x92,
	0xa9, 0x65, 0xde, 0xad, 0x2c, 0x48, 0x44, 0x70, 0xf7, 0xb7, 0x33, 0x70, 0x71, 0x5c, 0x4a, 0xc9,
	0x4b, 0x81, 0xe9, 0x92, 0xf1, 0x09, 0x2e, 0xd3, 0x8b, 0x86, 0xa5, 0x63, 0x2b, 0xac, 0x53, 0x41,
	0xd2, 0xb1, 0xe5, 0xdd, 0x61, 0x94, 0x31, 0xa5, 0x32, 0x02, 0x95, 0xd0, 0x08, 0x61, 0x15, 0xac,
	0xf2, 0xe6, 0x30, 0xa3, 0x94, 0xea, 0x47, 0xfa, 0xba, 0xf0, 0x73, 0xb8, 0x74, 0x4c, 0xc3, 0x3e,
	0xc5, 0xe3, 0xec, 0xd5, 0x54, 0x1c, 0xae, 0x2a, 0x85, 0x47, 0xa7, 0x8d, 0x6e, 0xc0, 0x55, 0xcd,
	0x25, 0x87, 0x7c, 0x2c, 0x5f, 0xc7, 0xf1, 0x9a, 0x52, 0xda, 0x38, 0xe4, 0x63, 0x4c, 0xb4, 0xe1,
	0x26, 0x39, 0xea, 0xe3, 0x2c, 0x67, 0x31, 0x4b, 0xfb, 0x34, 0xc4, 0xa3, 0x15, 0xaa, 0x1a, 0x9c,
	0xb8, 0x19, 0xe7, 0x6f, 0x90, 0xa3, 0xfe, 0xe3, 0x52, 0x75, 0xc4, 0x8f, 0x5b, 0x46, 0xd1, 0x3f,
	0xdb, 0x5e, 0x94, 0x0a, 0x9a, 0x1f, 0xc9, 0x60, 0x77, 0xac, 0x33, 0xed, 0xed, 0x1a, 0x45, 0x1f,
	0xb5, 0xe0, 0xfa, 0x64, 0x7b, 0x3a, 0x04, 0x74, 0x50, 0x5d, 0x99, 0x60, 0x4a, 0x85, 0x45, 0x59,
	0x5e, 0xdc, 0x2e, 0x38, 0x2a, 0x99, 0x0b, 0x31, 0xa0, 0xa9, 0xcc, 0x11, 0x41, 0xab, 0x8a, 0xf1,
	0x09, 0xcc, 0xc8, 0x6b, 0xb2, 0xe9, 0xcc, 0x37, 0xc7, 0x14, 0xe4, 0xe6, 0x80, 0xc4, 0x31, 0x4d,
	0xfb, 0x15, 0xc7, 0x53, 0x0c, 0xf7, 0x63, 0x58, 0xf4, 0x69, 0xdc, 0xeb, 0x52, 0x5e, 0x5e, 0x83,
	0xd1, 0x1a, 0x34, 0x42, 0x2a, 0x48, 0x14, 0xd3, 0x2a, 0x46, 0xcb, 0xb5, 0xbb, 0x09, 0xf6, 0x50,
	0xdd, 0x3c, 0x7c, 0x05, 0xea, 0x19, 0xe1, 0xbc, 0xd2, 0x36, 0x2b, 0x29, 0xcf, 0x69, 0xc6, 0x72,
	0xa1, 0xb6, 0x35, 0xeb, 0x99, 0x95, 0xbb, 0x06, 0x8e, 0x2f, 0x47, 0x5d, 0x75, 0x31, 0x7f, 0xf3,
	0xd9, 0xee, 0x65, 0xb8, 0x34, 0x06, 0x33, 0x17, 0xf7, 0xdf, 0xd7, 0x00, 0xf9, 0x54, 0x48, 0xd9,
	0x3e, 0x0b, 0x69, 0xb9, 0xdf, 0x16, 0x58, 0x79, 0x0f, 0x27, 0x2c, 0x2c, 0x27, 0xf2, 0x8f, 0xc6,
	0x9c, 0xff, 0x34, 0x6f, 0xdd, 0xeb, 0xa9, 0x55, 0x3d, 0x57, 0xbf, 0xe8, 0x53, 0xb8, 0x14, 0x46,
	0x5c, 0xde, 0xd8, 0x70, 0xcc, 0x38, 0xc7, 0xac, 0x87, 0x03, 0x96, 0x24, 0xb8, 0x17, 0x46, 0xb9,
	0x1c, 0x36, 0xf5, 0x05, 0x4f, 0x6b, 0xec, 0x31, 0xce, 0x3b, 0xbd, 0x26, 0x4b, 0x92, 0x47, 0x61,
	0x94, 0xcb, 0xf6, 0xa4, 0x2f, 0x82, 0x38, 0x2f, 0x62, 0xca, 0x31, 0x3b, 0xa2, 0x79, 0x1e, 0x85,
	0x54, 0x4f, 0x09, 0x0d, 0x6f, 0x49, 0xa3, 0x9e, 0x04, 0x3b, 0x06, 0x73, 0x37, 0xa1, 0xae, 0x77,
	0x80, 0xea, 0x50, 0xf3, 0x9e, 0xd9, 0xef, 0xa1, 0x06, 0xcc, 0xec, 0x6e, 0xed, 0xb5, 0xec, 0x29,
	0x29, 0xe9, 0x3e, 0xb3, 0x6b, 0xc8, 0x82, 0xe9, 0xe6, 0xc6, 0x9e, 0x3d, 0x2d, 0xa1, 0x03, 0xbf,
	0xe5, 0xa9, 0xe9, 0xbb, 0xde, 0xee, 0xc8, 0x19, 0xdd, 0xfe, 0xd3, 0xb4, 0xbb, 0x0c, 0x4b, 0x6f,
	0x1c, 0xcc, 0x38, 0xea, 0x89, 0xae, 0x16, 0xbe, 0xfa, 0x8e, 0xd1, 0x8b, 0xfa, 0xa5, 0xa7, 0xe4,
	0x20, 0x38, 0xfc, 0x9a, 0x72, 0xd6, 0x20, 0x18, 0xf1, 0x81, 0xa1, 0x42, 0x58, 0xfd, 0x77, 0x7b,
	0x7a, 0xc2, 0x1c, 0xb1, 0x6b, 0x42, 0x60, 0x1f, 0x96, 0x8a, 0x2c, 0x24, 0xb2, 0x52, 0xbf, 0xf3,
	0x03, 0x2e, 0x18, 0xe6, 0x50, 0xe4, 0xae, 0xe8, 0xfd, 0x6f, 0xbf, 0xb5, 0x7f, 0xf7, 0xe9, 0xe8,
	0x97, 0x9b, 0xd1, 0xe7, 0xff, 0x8f, 0x07, 0xfb, 0x69, 0x13, 0x66, 0xf5, 0x67, 0x22, 0x39, 0x89,
	0xbd, 0x71, 0x59, 0x3a, 0x0f, 0xb3, 0xcd, 0x4e, 0xbb, 0xdd, 0x52, 0xd7, 0x9b, 0x29, 0xb9, 0xf4,
	0x5b, 0x1b, 0x5e, 0x73, 0x47, 0xde, 0x9e, 0x6a, 0xa3, 0x57, 0xa9, 0xe9, 0xcd, 0xd5, 0x5f, 0x2d,
	0xeb, 0xaf, 0x57, 0xeb, 0x01, 0x4b, 0x46, 0xbe, 0x60, 0x1d, 0xd6, 0xd5, 0x67, 0xab, 0xfb, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x43, 0xe0, 0xc3, 0xe7, 0x2e, 0x13, 0x00, 0x00,
}
