FROM golang:1.25.0 AS builder

WORKDIR /usr/src/app

COPY go.mod go.sum ./
COPY vendor ./
RUN go mod tidy

COPY . .
RUN CGO_ENABLED=0 go build -o /usr/local/bin/exporter ./cmd/starlink_exporter/main.go

FROM alpine:3.22.0

COPY --from=builder /usr/local/bin/exporter /usr/bin/exporter

CMD ["/usr/bin/exporter"]
