{
 "title": "NTP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Time Offset (ms)",
   "type": "timeseries",
   "description": "Last Offset: This is the estimated local offset on the last clock update. \n\nRMS Offset: This is a long-term average of the offset value. \n\nSystem Time: Offset with NTP",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\r\ntimestop = uint(v: v.timeRangeStop)\r\nduration = duration(v:timestop - timestart)\r\n\r\ndata = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"last_offset\")\r\n    |> map(fn: (r) => ({r with _value: r._value * 1000.0}))\r\n\r\nyield data\r\n"
    },
    {
     "query": "rms_offset = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"rms_offset\")\r\n    |> map(fn: (r) => ({r with _value: r._value * 1000.0}))\r\n\r\nyield rms_offset\r\n"
    },
    {
     "query": "system_time = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"system_time\")\r\n    |> map(fn: (r) => ({r with _value: r._value * 1000.0}))\r\n\r\nyield system_time\r\n"
    }
   ]
  },
  {
   "title": "Root Difference (Seconds)",
   "type": "timeseries",
   "description": "Root delay\nThis is the total of the network path delays to the stratum-1 computer from which the computer is ultimately synchronized.\n\nRoot Dispersion\nThis is the total dispersion accumulated through all the computers back to the stratum-1 computer from which the computer is ultimately synchronized. Dispersion is due to system clock resolution, statistical measurement variations etc. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\r\ntimestop = uint(v: v.timeRangeStop)\r\nduration = duration(v:timestop - timestart)\r\n\r\ndata = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"root_dispersion\")\r\n\r\nyield data\r\n"
    },
    {
     "query": "timestart = uint(v: v.timeRangeStart)\r\ntimestop = uint(v: v.timeRangeStop)\r\nduration = duration(v:timestop - timestart)\r\n\r\nroot_delay = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"root_delay\")\r\n\r\nyield root_delay\r\n"
    }
   ]
  },
  {
   "title": "Skew (ppm)",
   "type": "timeseries",
   "description": "This is the estimated error bound on the frequency. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\r\ntimestop = uint(v: v.timeRangeStop)\r\nduration = duration(v:timestop - timestart)\r\n\r\ndata = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"skew\")\r\n\r\nyield data\r\n"
    }
   ]
  },
  {
   "title": "Frequency (ppm)",
   "type": "timeseries",
   "description": "Negative: slow",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\r\ntimestop = uint(v: v.timeRangeStop)\r\nduration = duration(v:timestop - timestart)\r\n\r\ndata = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"frequency\")\r\n\r\nyield data\r\n"
    }
   ]
  },
  {
   "title": "Update Interval (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\r\ntimestop = uint(v: v.timeRangeStop)\r\nduration = duration(v:timestop - timestart)\r\n\r\ndata = from(bucket: \"telegraf\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"chrony\" and r._field == \"update_interval\")\r\n\r\nyield data\r\n"
    }
   ]
  }
 ]
}