{
 "title": "Starlink",
 "description": "Starlink dish metrics",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "DishID",
    "label": "Dish ID",
    "query": {
     "query": "label_values(starlink_dish_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dish Location",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "starlink_dish_location_info{instance=\"$DishID\"}"
    }
   ]
  },
  { "title": "Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Dish Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_uptime_seconds{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "GPS Sats ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_gps_sats{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Obstructed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_currently_obstructed{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Roaming",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_roaming{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Connected GPS Satellites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "starlink_dish_gps_sats{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Pop Ping Drop Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "starlink_dish_pop_ping_drop_ratio{instance=\"$DishID\"} * 100"
    }
   ]
  },
  {
   "title": "Country Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ country_code }}"
    }
   ]
  },
  {
   "title": "Device ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ device_id }}"
    }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ hardware_version }}"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ software_version }}"
    }
   ]
  },
  {
   "title": "Location Request Mode",
   "type": "stat",
   "description": "LOCAL, NONE",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{ location_request_mode }}"
    }
   ]
  },
  {
   "title": "Dish Mobility Class",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_mobility_class{instance=\"$DishID\"}",
     "legendFormat": "{{ mobility_class }}"
    }
   ]
  },
  {
   "title": "Boot Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_boot_count{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(starlink_dish_pop_ping_latency_seconds{instance=\"$DishID\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Tail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starlink_dish_uplink_throughput_bytes{instance=\"$DishID\"} / 1000000 * -1",
     "legendFormat": "Upload"
    },
    {
     "expr": "starlink_dish_downlink_throughput_bytes{instance=\"$DishID\"} / 1000000",
     "legendFormat": "Download"
    }
   ]
  }
 ]
}