{
 "title": "Starlink-Updated",
 "description": "Starlink dish metrics",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "DishID",
    "label": "Dish ID",
    "query": {
     "query": "label_values(starlink_dish_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Router Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_uptime_s{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Country Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_info{instance=\"$DishID\"}",
     "legendFormat": "{{ country_code }}"
    }
   ]
  },
  {
   "title": "Router ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_info{instance=\"$DishID\"}",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_info{instance=\"$DishID\"}",
     "legendFormat": "{{ hardware_version }}"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_info{instance=\"$DishID\"}",
     "legendFormat": "{{ software_version }}"
    }
   ]
  },
  {
   "title": "IPv4 WAN Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_ipv4_wan_address{instance=\"$DishID\"}",
     "legendFormat": "{{ ipv4_wan_address }}"
    }
   ]
  },
  {
   "title": "Boot Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_info{instance=\"$DishID\"}",
     "legendFormat": "{{ boot_count }}"
    }
   ]
  },
  {
   "title": "Ping Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "starlink_router_router_ping_latency_ms{instance=\"$DishID\"}",
     "legendFormat": "Router Ping Latency"
    },
    {
     "expr": "starlink_router_router_pop_ping_latency_ms{instance=\"$DishID\"}",
     "legendFormat": "Router POP Ping Latency"
    },
    {
     "expr": "starlink_router_router_to_dish_ping_latency_ms{instance=\"$DishID\"}",
     "legendFormat": "Router To Dish Latency"
    }
   ]
  },
  {
   "title": "Last Boot Reason",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_info{instance=\"$DishID\"}",
     "legendFormat": "{{ last_boot_reason }}"
    }
   ]
  },
  {
   "title": "Duplex",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_ethernet_interface{instance=\"$DishID\",name=\"eth0\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "starlink_router_ethernet_interface{instance=\"$DishID\",name=\"eth0\"}",
     "legendFormat": "{{ duplex }}"
    }
   ]
  },
  {
   "title": "Duplex",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_router_ethernet_interface{instance=\"$DishID\",name=\"eth1\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "starlink_router_ethernet_interface{instance=\"$DishID\",name=\"eth1\"}",
     "legendFormat": "{{ duplex }}"
    }
   ]
  },
  { "title": "Dish Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_uptime_seconds{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "GPS Sats ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_gps_sats{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Obstructed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_currently_obstructed{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Roaming",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_roaming{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Connected GPS Satellites",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "starlink_dish_gps_sats{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Pop Ping Drop Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "starlink_dish_pop_ping_drop_ratio{instance=\"$DishID\"}*100"
    }
   ]
  },
  {
   "title": "Country Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ country_code }}"
    }
   ]
  },
  {
   "title": "Device ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ device_id }}"
    }
   ]
  },
  {
   "title": "Boot Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_boot_count{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ hardware_version }}"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_info{instance=\"$DishID\"}",
     "legendFormat": "{{ software_version }}"
    }
   ]
  },
  {
   "title": "boresightAzimuthDeg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_bore_sight_azimuth_deg{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "boresightElevationDeg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_bore_sight_elevation_deg{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "Power Save Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{ power_save_mode  }}"
    }
   ]
  },
  {
   "title": "Level Dish Mode",
   "type": "stat",
   "description": "TILT_LIKE_NORMAL, FORCE_LEVEL",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{ level_dish_mode }}"
    }
   ]
  },
  {
   "title": "Location Request Mode",
   "type": "stat",
   "description": "LOCAL, NONE",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{ location_request_mode }}"
    }
   ]
  },
  {
   "title": "Snow Melt Mode",
   "type": "stat",
   "description": "AUTO, ALWAYS_ON, ALWAYS_OFF",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_dish_config{instance=\"$DishID\"}",
     "legendFormat": "{{ snow_melt_mode }}"
    }
   ]
  },
  {
   "title": "isHeating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_is_heating{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_alert_slow_eth_speeds{instance=\"$DishID\"}",
     "legendFormat": "Slow Ethernet"
    },
    {
     "expr": "starlink_dish_alert_mast_not_near_vertical{instance=\"$DishID\"}",
     "legendFormat": "Mast Not Near Vertical"
    },
    {
     "expr": "starlink_dish_alert_motors_stuck{instance=\"$DishID\"}",
     "legendFormat": "Motor Stuck"
    },
    {
     "expr": "starlink_dish_alert_thermal_throttle{instance=\"$DishID\"}",
     "legendFormat": "Thernal Throttle"
    },
    {
     "expr": "starlink_dish_alert_thermal_shutdown{instance=\"$DishID\"}",
     "legendFormat": "Thermal Shutdown"
    },
    {
     "expr": "starlink_dish_alert_unexpected_location{instance=\"$DishID\"}",
     "legendFormat": "Unexpected Location"
    }
   ]
  },
  {
   "title": "Tail",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "starlink_dish_uplink_throughput_bytes{instance=\"$DishID\"} / 1000000 * -1",
     "legendFormat": "Upload"
    },
    {
     "expr": "starlink_dish_downlink_throughput_bytes{instance=\"$DishID\"} /1000000",
     "legendFormat": "Download"
    },
    {
     "expr": "avg_over_time(starlink_dish_pop_ping_latency_seconds{instance=\"$DishID\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "BoreSight Azimuth Degree",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "starlink_dish_bore_sight_azimuth_deg{instance=\"$DishID\"}"
    }
   ]
  },
  {
   "title": "BoreSight Elevation Degree",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "starlink_dish_bore_sight_elevation_deg{instance=\"$DishID\"}"
    }
   ]
  }
 ]
}