version: "3"
services:
  starlink_exporter:
    image: "clarkzjw/starlink_exporter:latest"
    restart: always
    ports:
      - "9817:9817"

  prometheus:
    image: "prom/prometheus:v2.37.9"
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=365d'
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./config/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./data/prometheus
        target: /prometheus

  grafana:
    image: "grafana/grafana-oss:10.0.3"
    restart: always
    user: "root"
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource, ae3e-plotly-panel
      - GF_LOG_CONSOLE_LEVEL=warn
    volumes:
      - type: bind
        source: ./data/grafana
        target: /var/lib/grafana
      - type: bind
        source: ./config/grafana/provisioning
        target: /etc/grafana/provisioning/

  influxdb:
    image: "influxdb:2.7"
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./config/influxdb:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=starlinkadmin
      - DOCKER_INFLUXDB_INIT_ORG=starlink
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_RETENTION=360d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=starlinkexporter
